### ISSUE TITLE
Discord missing

### ISSUE THREAD

**Issue by ghost** [ChaosBuffalo/BoneTown#1]
the discord link from reddit is outdated.
please update it with a new discord link
set this new link to be a timeless discord invitation so it last forever.
also please add a invitation to discord in here at github

i'm a 3d modeler and animator of roblox games and i wanna try the bone town but i have no idea how. so i wanna join in the dicord.

**Comment by Kovak** [comment]
Oh sorry about that, didn't know discord links expired automatically, here is a permanent one: https://discord.gg/mCXnxJ4
